apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-image
        image: instregistry.azurecr.io/dotnetapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
